microblog/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


from .views import RegistrationView


app_name = 'accounts'

urlpatterns = [
    # reverse()
    # {% url 'accounts:register' %} -> '/accounts/register'
    path('login', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', RegistrationView.as_view(), name='register'),
]

microblog/posts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path('', TemplateView.as_view(
         template_name='posts/index.html')),
]

microblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('', include('microblog.accounts.urls')),
    path('', include('microblog.posts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

microblog/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

microblog/posts/models.py
from django.db import models

# Create your models here.

microblog/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField

from .models import User


class RegistrationForm(UserCreationForm):
    # .......
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

microblog/accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView

from .forms import RegistrationForm


class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = 'accounts/registration.html'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        else:
            return super().dispatch(request, *args, **kwargs)

microblog/posts/views.py
from django.shortcuts import render
from django.views.generic import View


class HelloWorldView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'posts/index.html')


def hello_world(request):
    context = {
        'name': 'Piotr',
    }
    return render(request, 'posts/index.html', context)

microblog/accounts/templates/accounts/login.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Zaloguj">
</form>

microblog/accounts/templates/accounts/registration.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Zarejestruj">
</form>

microblog/posts/templates/posts/index.html
<html>

<head>
    <title>Mikroblog</title>
</head>

<body>
    <p>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Wyloguj</a>
        {% else %}
            <a href="{% url 'accounts:login' %}">Zaloguj się</a> lub <a href="{% url 'accounts:register' %}">Zarejestruj</a>
        {% endif %}
    </p>

    <p> {{ user }} </p>

    Hello world!
</body>
</html>